import { NextRequest, NextResponse } from 'next/server';
import { getAudit } from '@/lib/db';
import { AuditResult, AuditEntry } from '@/lib/ieepa-engine';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

// NOTE: CAPE portal spec not yet published — update this format when CBP releases official spec.
// Current column order follows anticipated CBP CAPE requirements based on protest filing conventions.

function escapeCsvField(val: string | number | undefined | null): string {
  const s = String(val ?? '');
  if (s.includes(',') || s.includes('"') || s.includes('\n')) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

function buildCapeRow(entry: AuditEntry): string {
  const fields = [
    escapeCsvField(entry.entry_number),
    escapeCsvField(entry.entry_date),
    escapeCsvField(''), // Port Code — may not be on all entries
    escapeCsvField(''), // Importer of Record Number — user must fill
    escapeCsvField(entry.ieepa_code),
    escapeCsvField(entry.duty_amount.toFixed(2)),
  ];
  return fields.join(',');
}

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ auditId: string }> }
): Promise<NextResponse> {
  try {
    const { auditId } = await params;

    const record = await getAudit(auditId);
    if (!record) {
      return NextResponse.json({ error: 'Audit not found' }, { status: 404 });
    }

    if (record.status !== 'paid') {
      return NextResponse.json(
        { error: 'Payment required to download the CAPE-ready CSV' },
        { status: 402 }
      );
    }

    const storedData = JSON.parse(record.data) as { audit: AuditResult };
    const audit = storedData.audit;

    const refundableEntries = audit.ieepa_entries.filter((e) => e.is_refundable);

    const headerComment =
      '# CAPE Portal Filing CSV\n' +
      '# Generated by IEEPA Refund Tool\n' +
      '# NOTE: CAPE portal spec not yet published by CBP. Update format when official spec released (~April 20, 2026).\n' +
      '# Fill in Port Code and Importer of Record Number before submitting.\n' +
      '#\n';

    const csvHeader = 'Entry Summary Number,Entry Date,Port Code,Importer of Record Number,IEEPA HTS Code,IEEPA Duty Amount\n';

    const dataRows = refundableEntries.map(buildCapeRow).join('\n');

    const csvContent = headerComment + csvHeader + dataRows;

    return new NextResponse(csvContent, {
      status: 200,
      headers: {
        'Content-Type': 'text/csv; charset=utf-8',
        'Content-Disposition': `attachment; filename="ieepa-refund-cape-${auditId}.csv"`,
      },
    });
  } catch (err) {
    console.error('[cape-csv] error:', err);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
